import { NextResponse } from 'next/server'

// GET /api/seo/tools
// Lists ALL built-in SEO tools — the full set inspired by Open SEO + Seonaut.
// These run directly inside VirtuaLab Digital, no external endpoint needed
// (except where noted: DataForSEO for backlinks/competitors, GSC for rank tracking).

export async function GET() {
  return NextResponse.json({
    tools: [
      // ─── Audit & Analysis (built-in, run on a URL) ───
      {
        id: 'audit',
        label: 'Full SEO Audit',
        icon: 'ClipboardCheck',
        category: 'audit',
        description: 'Complete 17-check audit: meta tags, schema, broken links, page speed, local SEO, mobile, images, headings.',
        endpoint: '/api/seo/audit',
        method: 'POST',
        input: 'url-or-project',
        builtin: true,
      },
      {
        id: 'broken-links',
        label: 'Broken Link Checker',
        icon: 'Unlink',
        category: 'audit',
        description: 'Crawl internal links + find 404s, 5xx errors, and dead links.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'redirects',
        label: 'Redirect Checker',
        icon: 'CornerDownRight',
        category: 'audit',
        description: 'Check redirect chains, 301 vs 302, and redirect loops.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'headings',
        label: 'Heading Structure Analyzer',
        icon: 'List',
        category: 'audit',
        description: 'Analyze H1–H6 hierarchy, order, and missing/duplicate headings.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'images-alt',
        label: 'Image Alt Text Checker',
        icon: 'ImageOff',
        category: 'audit',
        description: 'Find images missing alt text — accessibility + image SEO.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'internal-links',
        label: 'Internal Link Analyzer',
        icon: 'Link2',
        category: 'audit',
        description: 'Analyze internal vs external link structure, anchor texts.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'canonical',
        label: 'Canonical Checker',
        icon: 'Link',
        category: 'audit',
        description: 'Check canonical URL presence + validity to prevent duplicate content.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'duplicate-content',
        label: 'Duplicate Content Checker',
        icon: 'Copy',
        category: 'audit',
        description: 'Detect duplicate title/H1/description combinations.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },

      // ─── Performance (built-in) ───
      {
        id: 'page-speed',
        label: 'Page Speed Checker',
        icon: 'Gauge',
        category: 'performance',
        description: 'TTFB, total load time, HTML size, image count — Core Web Vitals basics.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'mobile-friendly',
        label: 'Mobile-Friendly Test',
        icon: 'Smartphone',
        category: 'performance',
        description: 'Viewport meta, responsive readiness, page weight on mobile.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },

      // ─── Content (built-in + AI) ───
      {
        id: 'keyword-density',
        label: 'Keyword Density Analyzer',
        icon: 'Hash',
        category: 'content',
        description: 'Top keywords by frequency, density %, content focus analysis.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'readability',
        label: 'Content Readability Checker',
        icon: 'BookOpen',
        category: 'content',
        description: 'Word count, sentence count, avg words per sentence, reading level.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'title-optimizer',
        label: 'Title Tag Optimizer',
        icon: 'Type',
        category: 'content',
        description: 'Title tag length, SERP preview, optimization suggestions.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'meta-desc',
        label: 'Meta Description Optimizer',
        icon: 'AlignLeft',
        category: 'content',
        description: 'Meta description length, SERP preview, optimization suggestions.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },

      // ─── Technical SEO (built-in) ───
      {
        id: 'robots-txt',
        label: 'Robots.txt Checker',
        icon: 'Bot',
        category: 'technical',
        description: 'Fetch + analyze robots.txt: user-agents, disallow rules, sitemap refs.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'sitemap-validator',
        label: 'Sitemap Validator',
        icon: 'Map',
        category: 'technical',
        description: 'Validate sitemap.xml: XML structure, URL count, accessibility.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'schema-validator',
        label: 'Schema Validator (JSON-LD)',
        icon: 'Braces',
        category: 'technical',
        description: 'Validate structured data blocks, list schema types.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'hreflang',
        label: 'Hreflang Checker',
        icon: 'Languages',
        category: 'technical',
        description: 'Check hreflang tags for international SEO + language alternates.',
        endpoint: '/api/seo/check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },
      {
        id: 'sitemap-gen',
        label: 'XML Sitemap Generator',
        icon: 'FileCode',
        category: 'technical',
        description: 'Generate a sitemap.xml from your project\'s pages.',
        endpoint: '/api/seo/sitemap-check',
        method: 'GET',
        input: 'project',
        builtin: true,
      },

      // ─── Preview ───
      {
        id: 'meta-check',
        label: 'Meta Tag Preview',
        icon: 'Search',
        category: 'preview',
        description: 'See how your page looks in Google + social shares (OG + Twitter card).',
        endpoint: '/api/seo/meta-check',
        method: 'POST',
        input: 'url',
        builtin: true,
      },

      // ─── Research & Tracking (needs external API) ───
      {
        id: 'keyword-research',
        label: 'Keyword Research',
        icon: 'SearchCode',
        category: 'research',
        description: 'AI-suggested keywords grouped by intent (informational, commercial, local).',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },
      {
        id: 'rank-tracker',
        label: 'Rank Tracker',
        icon: 'TrendingUp',
        category: 'research',
        description: 'Track keyword rankings over time. Uses Google Search Console — connect GSC MCP first.',
        endpoint: null,
        method: 'external',
        input: 'none',
        builtin: false,
        needsIntegration: 'Google Search Console MCP',
      },
      {
        id: 'competitor-insights',
        label: 'Competitor Insights',
        icon: 'Users',
        category: 'research',
        description: 'Analyze competitor keywords, traffic, and gaps. Needs DataForSEO API key.',
        endpoint: null,
        method: 'external',
        input: 'none',
        builtin: false,
        needsApiKey: 'DataForSEO',
      },
      {
        id: 'backlinks',
        label: 'Backlink Profile',
        icon: 'Link2',
        category: 'research',
        description: 'Analyze backlinks, referring domains, anchor text. Needs DataForSEO API key.',
        endpoint: null,
        method: 'external',
        input: 'none',
        builtin: false,
        needsApiKey: 'DataForSEO',
      },
      {
        id: 'ai-visibility',
        label: 'AI Visibility (AEO/GEO)',
        icon: 'Sparkles',
        category: 'research',
        description: 'Check if your content appears in AI answers (ChatGPT, Perplexity, Google AI Overviews).',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },

      // ─── AI Tools (use /api/ai/chat) ───
      {
        id: 'content-brief',
        label: 'Content Brief Generator',
        icon: 'FileText',
        category: 'ai',
        description: 'Generate an SEO content brief: target keyword, headings, word count, internal links.',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },
      {
        id: 'schema-gen',
        label: 'Schema Generator (JSON-LD)',
        icon: 'Code2',
        category: 'ai',
        description: 'Generate LocalBusiness / FAQ / Article JSON-LD schema for your page.',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },
      {
        id: 'meta-title-gen',
        label: 'Meta Title Generator',
        icon: 'Type',
        category: 'ai',
        description: 'AI-generate optimized meta titles for your pages.',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },
      {
        id: 'meta-desc-gen',
        label: 'Meta Description Generator',
        icon: 'AlignLeft',
        category: 'ai',
        description: 'AI-generate optimized meta descriptions under 160 chars.',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },
      {
        id: 'content-rewriter',
        label: 'Content Rewriter',
        icon: 'RefreshCw',
        category: 'ai',
        description: 'Rewrite existing content for better SEO + readability.',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },
      {
        id: 'faq-generator',
        label: 'FAQ Generator',
        icon: 'HelpCircle',
        category: 'ai',
        description: 'Generate FAQ sections with schema-ready questions + answers.',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },

      // ─── SEO Strategy Tools (AI-powered, for agency/freelancer use) ───
      {
        id: 'hub-spoke-generator',
        label: 'Hub & Spoke Generator',
        icon: 'Network',
        category: 'strategy',
        description: 'Generate a hub-and-spoke content architecture: one pillar page (hub) + 8-12 supporting cluster pages (spokes) with internal link map. For topical authority.',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },
      {
        id: 'semantic-generator',
        label: 'Semantic SEO Generator',
        icon: 'Brain',
        category: 'strategy',
        description: 'Generate semantically related terms, entities, and topics for a target keyword. Builds a semantic cluster Google expects to see in comprehensive content.',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },
      {
        id: 'global-seo-generator',
        label: 'Global SEO Generator',
        icon: 'Globe',
        category: 'strategy',
        description: 'Generate an international SEO strategy: hreflang map, country-specific landing pages, local keyword variations, currency/language considerations. For multi-country targeting.',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },
      {
        id: 'national-seo-generator',
        label: 'National SEO Generator',
        icon: 'Flag',
        category: 'strategy',
        description: 'Generate a national-scale SEO strategy for a single country: national keyword clusters, major-city landing pages, brand vs non-brand split, competitor gap analysis.',
        endpoint: '/api/ai/chat',
        method: 'POST',
        input: 'text',
        builtin: true,
        ai: true,
      },
    ],
    categories: [
      { id: 'audit', label: 'Audit & Analysis' },
      { id: 'performance', label: 'Performance' },
      { id: 'content', label: 'Content' },
      { id: 'technical', label: 'Technical SEO' },
      { id: 'preview', label: 'Preview' },
      { id: 'research', label: 'Research & Tracking' },
      { id: 'strategy', label: 'SEO Strategy' },
      { id: 'ai', label: 'AI Tools' },
    ],
    note: 'All built-in tools run directly inside VirtuaLab Digital — no external endpoint needed (except Rank Tracker → GSC, Competitor Insights + Backlinks → DataForSEO API). Inspired by the open-source Open SEO + Seonaut toolkits.',
  })
}
